### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by shraysaxena88** [ds4owd-001/md-02-assignments-Shraysaxena88#1]
@larnsce @mianzg @sskorik01 

Did I do the commit/push correctly? I completed the assignment but don't understand this step well. 

Thanks.

**Comment by larnsce** [comment]
Thanks for working through the assignment. I do not see any changes committed and pushed to GitHub. What do you see when you interact with Git in the top-right window of RStudio. Can you share a screenshot, please?

The steps are documented here: https://ds4owd-001.github.io/website/assignments/md-02/am-02-1-data-visualisation.html#step-2-commit-and-push-your-changes

**Comment by shraysaxena88** [comment]
@larnsce - I think I may have missed the push step earlier. 
I think I did it correctly now.

**Comment by larnsce** [comment]
Yes, you have. Great job! You can see a list of all commits here: https://github.com/ds4owd-001/md-02-assignments-Shraysaxena88/commits/main

I will close the issue for you now.
